---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Homepage extraordinaire"
subtitle: "The World of Dan"
logo: "assets/logo.png"
#icon: "fas fa-skull-crossbones"

# Optional message
#
#message:
#  # url: https://....
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  content: "This is a dummy homepage demo. Find more information on github.com/bastienwirtz/homer"

# Optional navbar
links:
  - name: "maker.rip"
    icon: "fab fa-wordpress"
    url: "https://maker.rip/"
  - name: "maker.rip"
    icon: "fab fa-instagram"
    url: "https://instagram.com/maker.rip/"
  - name: "monumental.me"
    icon: "fab fa-instagram"
    url: "https://instagram.com/monumental.me/"
  - name: "maker.rip"
    icon: "fab fa-twitter"
    url: "https://twitter.com/maker.rip/"
  - name: "monumental_me"
    icon: "fab fa-twitter"
    url: "https://twitter.com/monumental_me/"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Foxsoft"
    icon: "fas fa-dog"
    items:
      - name: "ClickUp"
        logo: "assets/tools/clickup.png"
        subtitle: "Project management tool"
        tag: "pm"
        url: "https://app.clickup.com/"
      - name: "Teamwork"
        logo: "assets/tools/teamwork.png"
        subtitle: "Project management tool"
        tag: "pm"
        url: "https://foxsoft.eu.teamwork.com/"
      - name: "Tettra"
        logo: "assets/tools/tettra.jpg"
        subtitle: "Company Wiki"
        tag: "wiki"
        url: "https://app.tettra.co/teams/foxsoft/"
      - name: "Amigo"
        logo: "assets/tools/amigo.jpg"
        subtitle: "Customer tracking tool"
        tag: "customer"
        url: "https://amigo.collige.re/"
      - name: "Pipedrive"
        logo: "assets/tools/pipedrive.png"
        subtitle: "Customer relation management"
        tag: "crm"
        url: "https://foxsoft.pipedrive.com/"
      - name: "Helpscout"
        logo: "assets/tools/helpscout.png"
        subtitle: "Customer support"
        tag: "support"
        url: "https://secure.helpscout.net/"
      - name: "makandra cards"
        logo: "assets/tools/makandracards.png"
        subtitle: "Knowledge base"
        tag: "knowledge"
        url: "https://makandracards.com/foxsoft"
      - name: "Timetastic"
        logo: "assets/tools/timetastic.svg"
        subtitle: "Holidays and time off"
        tag: "holiday"
        url: "https://app.timetastic.co.uk/wallchart"
  - name: "DevOps"
    icon: "fas fa-code-branch"
    items:
      - name: "GitLab"
        logo: "assets/tools/gitlab.png"
        subtitle: "Git repository storage"
        tag: "git"
        url: "https://git.foxsoft.co.uk/"
      - name: "Cloud 66"
        logo: "assets/tools/cloud66.png"
        subtitle: "Rails deployment"
        tag: "deployment"
        url: "https://app.cloud66.com/"
      - name: "AppSignal"
        logo: "assets/tools/appsignal.png"
        subtitle: "Server monitoring"
        tag: "monitoring"
        url: "https://appsignal.com/"
      - name: "Mailtrap"
        logo: "assets/tools/mailtrap.png"
        subtitle: "Email interception"
        tag: "email"
        url: "https://mailtrap.io/"
      - name: "Netlify"
        logo: "assets/tools/netlify.png"
        subtitle: "Static site hosting"
        tag: "hosting"
        url: "https://app.netlify.com/"
  - name: "Maker.RIP"
    icon: "fas fa-hammer"
    items:
      - name: "Basecamp"
        logo: "assets/tools/basecamp.png"
        subtitle: "Project management"
        tag: "pm"
        url: "https://3.basecamp.com/4331655/"
      - name: "Hubspot"
        logo: "assets/tools/hubspot.png"
        subtitle: "Customer relation management"
        tag: "crm"
        url: "https://app.hubspot.com/"
