---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Homepage extraordinaire"
subtitle: "The World of Dan"
logo: "assets/logo.png"
#icon: "fas fa-skull-crossbones"

# Optional message
#
#message:
#  # url: https://....
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  content: "This is a dummy homepage demo. Find more information on github.com/bastienwirtz/homer"

# Optional navbar
links:
  - name: "YNAB"
    icon: "fas fa-piggy-bank"
    url: "https://app.youneedabudget.com/"
  - name: "Halifax"
    icon: "fas fa-money-check"
    url: "https://www.halifax-online.co.uk/personal/logon/login.jsp"
  - name: "Super Simple RGB WiFi Lamp"
    icon: "fas fa-lightbulb"
    url: "http://super-simple-rgb-wifi-lamp.local/"
  - name: "Estimates"
    icon: "fas fa-business-time"
    url: "https://airtable.com/tblIQXlIVF2qayrMC/viw42ubYn7GDdTZdx"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Foxsoft"
    icon: "fas fa-dog"
    items:
      - name: "ClickUp"
        logo: "assets/tools/clickup.png"
        subtitle: "Project management tool"
        tag: "pm"
        url: "https://app.clickup.com/"
      - name: "Teamwork"
        logo: "assets/tools/teamwork.png"
        subtitle: "Project management tool"
        tag: "pm"
        url: "https://foxsoft.eu.teamwork.com/"
      - name: "Tettra"
        logo: "assets/tools/tettra.jpg"
        subtitle: "Company Wiki"
        tag: "wiki"
        url: "https://app.tettra.co/teams/foxsoft/"
      - name: "Amigo"
        logo: "assets/tools/amigo.jpg"
        subtitle: "Customer tracking tool"
        tag: "customer"
        url: "https://amigo.collige.re/"
      - name: "Pipedrive"
        logo: "assets/tools/pipedrive.png"
        subtitle: "Customer relation management"
        tag: "crm"
        url: "https://foxsoft.pipedrive.com/"
      - name: "Helpscout"
        logo: "assets/tools/helpscout.png"
        subtitle: "Customer support"
        tag: "support"
        url: "https://secure.helpscout.net/mailbox/0f7b7db7882a2e53/192288/"
      - name: "Support Project Timers"
        logo: "assets/tools/clickup.png"
        subtitle: "Customer support"
        tag: "support"
        url: "https://support-contracts.herokuapp.com/"
      - name: "makandra cards"
        logo: "assets/tools/makandracards.png"
        subtitle: "Knowledge base"
        tag: "knowledge"
        url: "https://makandracards.com/foxsoft"
      - name: "Timetastic"
        logo: "assets/tools/timetastic.svg"
        subtitle: "Holidays and time off"
        tag: "holiday"
        url: "https://app.timetastic.co.uk/wallchart"
  - name: "DevOps"
    icon: "fas fa-code-branch"
    items:
      - name: "GitLab"
        logo: "assets/tools/gitlab.png"
        subtitle: "Git repository storage"
        tag: "git"
        url: "https://git.foxsoft.co.uk/"
      - name: "Cloud 66"
        logo: "assets/tools/cloud66.png"
        subtitle: "Rails deployment"
        tag: "deployment"
        url: "https://app.cloud66.com/"
      - name: "AppSignal"
        logo: "assets/tools/appsignal.png"
        subtitle: "Server monitoring"
        tag: "monitoring"
        url: "https://appsignal.com/"
      - name: "Mailtrap"
        logo: "assets/tools/mailtrap.png"
        subtitle: "Email interception"
        tag: "email"
        url: "https://mailtrap.io/"
      - name: "Heroku"
        logo: "assets/tools/heroku.png"
        subtitle: "Dynamic app hosting"
        tag: "hosting"
        url: "https://dashboard.heroku.com/"
      - name: "Digitalocean"
        logo: "assets/tools/digitalocean.png"
        subtitle: "Dynamic server"
        tag: "hosting"
        url: "https://cloud.digitalocean.com/"
      - name: "Netlify"
        logo: "assets/tools/netlify.png"
        subtitle: "Static site hosting"
        tag: "hosting"
        url: "https://app.netlify.com/"
      - name: "Gandi"
        logo: "assets/tools/gandi.png"
        subtitle: "Domain registration"
        tag: "domains"
        url: "https://admin.gandi.net/"
      - name: "123-Reg"
        logo: "assets/tools/123reg.png"
        subtitle: "Domain registration"
        tag: "domains"
        url: "https://www.123-reg.co.uk/secure"
  - name: "Maker.RIP"
    icon: "fas fa-hammer"
    items:
      - name: "Basecamp"
        logo: "assets/tools/basecamp.png"
        subtitle: "Project management"
        tag: "pm"
        url: "https://3.basecamp.com/4331655/"
      - name: "Capsule"
        logo: "assets/tools/capsulecrm.png"
        subtitle: "Customer relation management"
        tag: "crm"
        url: "https://makerrip.capsulecrm.com/"
      - name: "MailerLite"
        logo: "assets/tools/mailerlite.png"
        subtitle: "Email subscription"
        tag: "email"
        url: "https://app.mailerlite.com/"
      - name: "Maker.RIP"
        logo: "assets/tools/instagram.png"
        subtitle: "Instagram"
        tag: "social media"
        url: "https://instagram.com/maker.rip/"
      - name: "Monumental Me"
        logo: "assets/tools/instagram.png"
        subtitle: "Instagram"
        tag: "social media"
        url: "https://instagram.com/monumental.me/"
      - name: "Maker.RIP"
        logo: "assets/tools/twitter.png"
        subtitle: "Twitter"
        tag: "social media"
        url: "https://twitter.com/makerrip/"
      - name: "Monumental Me"
        logo: "assets/tools/twitter.png"
        subtitle: "Twitter"
        tag: "social media"
        url: "https://twitter.com/monumental_me/"
